export const ERROR_CODE = {
    UNAUTHORIZED: 'UNAUTHORIZED',
    FORBIDDEN: 'FORBIDDEN',
    NOT_FOUND: 'NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    SERVICE_NOT_CONFIGURED: 'SERVICE_NOT_CONFIGURED',
    INTERNAL_ERROR: 'INTERNAL_ERROR',
    OAUTH_CODE_MISSING: 'OAUTH_CODE_MISSING',
    OAUTH_STATE_MISMATCH: 'OAUTH_STATE_MISMATCH',
    OAUTH_EXCHANGE_FAILED: 'OAUTH_EXCHANGE_FAILED',
    OAUTH_PROFILE_FAILED: 'OAUTH_PROFILE_FAILED',
} as const

export type ErrorCode = (typeof ERROR_CODE)[keyof typeof ERROR_CODE]
